### ISSUE TITLE
Loading video while the intro is playing

### ISSUE THREAD

**Issue by iWin-R** [dkanada/jellyfin-plugin-intros#37] opened 2021-06-18 17:35 UTC
Currently, the intro has to play through before the video in question starts even **loading**. My suggestion is to play the intro while the video is loading in the background.

That way, there is no unnecessarily lost time in loading and we have a nice into to look at meanwhile.

**Comment by dkanada** [comment] 2021-06-21 14:39
This is a duplicate of #18 and would need to be handled by each individual client, so I suggest opening issues there instead.

**Closed by dkanada** 2021-06-21 14:39 UTC
