### ISSUE TITLE
Can't set up a directory for random prerolls (only a single specific preroll)

### ISSUE THREAD

**Issue by LeVraiRoiDHyrule** [dkanada/jellyfin-plugin-intros#35] opened 2021-06-07 12:26 UTC
Hi,

I've got a directory with all my random prerolls. I would like the addon to pick one different each time. If I set the direct path to a specific intro (like "/mnt/dietpi_userdata/JellyIntros/Elegant Short Jellyfin Pre-roll-443125346.mp4") it works perfectly.

But if I want to input the path to the folder ("/mnt/dietpi_userdata/JellyIntros/"), it doesn't work. It's like I didn't change anything, it still plays the single intro I've set before.

I confirm Jellyfin has read and execute permissions on that folder and all files in it.

Could someone help me ?
Any answer is welcome, have a great day

**Comment by dkanada** [comment] 2021-06-07 13:39
Duplicate of #28 with no estimate for a fix, but I'll close this one and track any progress over there.

**Closed** 2021-06-07 13:40 UTC
